// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDu6CMqD_7JMypMb6dcTUmiPXyidKK2s',
    appId: '1:77371563818:web:b45292b5f3d10bb655c853',
    messagingSenderId: '77371563818',
    projectId: 'napps-2951a',
    authDomain: 'napps-2951a.firebaseapp.com',
    storageBucket: 'napps-2951a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSNbXspKBRUzWY1Tqz2krUi92yfKpSjs',
    appId: '1:77371563818:android:925200963260793a55c853',
    messagingSenderId: '77371563818',
    projectId: 'napps-2951a',
    storageBucket: 'napps-2951a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBabjogE3X9St9Gzl_F-B8w83Fbw5VdTSw',
    appId: '1:77371563818:ios:dbfb9d82565de7d655c853',
    messagingSenderId: '77371563818',
    projectId: 'napps-2951a',
    storageBucket: 'napps-2951a.appspot.com',
    iosBundleId: 'com.example.pwdMng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBabjogE3X9St9Gzl_F-B8w83Fbw5VdTSw',
    appId: '1:77371563818:ios:b01f6e115fb1a11255c853',
    messagingSenderId: '77371563818',
    projectId: 'napps-2951a',
    storageBucket: 'napps-2951a.appspot.com',
    iosBundleId: 'com.example.pwdMng.RunnerTests',
  );
}
